#!/usr/bin/php
<?php
date_default_timezone_set('Europe/Lisbon');

require "lib/jobs.php";
require "lib/request.php";

// HTTP Request
$request = new Request('https://builds.apache.org/api/json?tree=jobs[name,lastBuild[result]]');

// get the list of jobs from jenkins API
$jobs = $request->getResults();

// insert on database
foreach ($jobs as $index => $job){
  $new_job = new Jobs($job['name'], $job['lastBuild']['result'] );
  $new_job->save();
}

// get all jobs from database
$jobs = Jobs::findAll();
while ($job = $jobs->fetchArray())
{
    echo $job['name']." ".$job['status']." ".$job["checked_date"] . PHP_EOL;
}
